# Generated by Django 5.1.1 on 2024-10-25 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_address',
            field=models.CharField(db_column='住所', max_length=255),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_city',
            field=models.CharField(db_column='市町村区', max_length=100),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_id',
            field=models.UUIDField(db_column='ゴルフ場ID', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_name',
            field=models.CharField(db_column='ゴルフ場名', max_length=255),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_phone_number',
            field=models.CharField(db_column='電話番号', max_length=11),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_prefecture',
            field=models.CharField(db_column='都道府県', max_length=40),
        ),
        migrations.AlterField(
            model_name='golfhousemaster',
            name='house_zipcode',
            field=models.CharField(db_column='郵便番号', max_length=8),
        ),
    ]
