# Generated by Django 5.1.1 on 2024-10-22 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_zipcode', models.CharField(max_length=8)),
                ('course_prefecture', models.CharField(max_length=40)),
                ('course_city', models.CharField(max_length=100)),
                ('course_address', models.CharField(max_length=255)),
                ('course_phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
