# Generated by Django 5.1.1 on 2024-11-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
