# Generated by Django 5.1.1 on 2024-11-03 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0002_player_name2'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_1',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_2',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_3',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_4',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_5',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_6',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_7',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_8',
        # ),
        # migrations.RemoveField(
        #     model_name='teeingareamaster',
        #     name='yard_9',
        # ),
        migrations.CreateModel(
            name='TeeingAreaMaster',
            fields=[
                ('teeing_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('teeing_area_name', models.CharField(max_length=255, verbose_name='ティーイングエリア名')),
                ('yard_1', models.IntegerField(blank=True, null=True)),
                ('yard_2', models.IntegerField(blank=True, null=True)),
                ('yard_3', models.IntegerField(blank=True, null=True)),
                ('yard_4', models.IntegerField(blank=True, null=True)),
                ('yard_5', models.IntegerField(blank=True, null=True)),
                ('yard_6', models.IntegerField(blank=True, null=True)),
                ('yard_7', models.IntegerField(blank=True, null=True)),
                ('yard_8', models.IntegerField(blank=True, null=True)),
                ('yard_9', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfScore_app.coursemaster')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfScore_app.golfhousemaster')),
            ],
        ),
        migrations.CreateModel(
            name='TeeingAreaYardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard_1', models.IntegerField(blank=True, null=True)),
                ('yard_2', models.IntegerField(blank=True, null=True)),
                ('yard_3', models.IntegerField(blank=True, null=True)),
                ('yard_4', models.IntegerField(blank=True, null=True)),
                ('yard_5', models.IntegerField(blank=True, null=True)),
                ('yard_6', models.IntegerField(blank=True, null=True)),
                ('yard_7', models.IntegerField(blank=True, null=True)),
                ('yard_8', models.IntegerField(blank=True, null=True)),
                ('yard_9', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfScore_app.coursemaster')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfScore_app.golfhousemaster')),
                ('teeing_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfScore_app.teeingareamaster')),
            ],
        ),
    ]
