# Generated by Django 5.1.1 on 2024-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0003_remove_teeingareamaster_yard_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_1',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_2',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_3',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_4',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_5',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_6',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_7',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_8',
        ),
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='yard_9',
        ),
    ]
