# Generated by Django 5.1.1 on 2024-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0003_coursemaster_create_at_coursemaster_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemaster',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
