# Generated by Django 5.1.1 on 2024-11-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0004_remove_teeingareamaster_yard_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teeingareamaster',
            name='course_id',
        ),
    ]
