# Generated by Django 5.1.1 on 2024-10-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0004_alter_coursemaster_create_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMaster',
            new_name='GolfHouseMaster',
        ),
    ]
