# Generated by Django 5.1.1 on 2024-11-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfScore_app', '0005_remove_teeingareamaster_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='ex_round',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='first_round',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round',
            name='green',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='play_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='second_round',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round',
            name='teeing_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='weather',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round',
            name='wind',
            field=models.CharField(max_length=255),
        ),
    ]
